### ISSUE TITLE
Libreelec new download address

### ISSUE THREAD

**Issue by davidcsgf** [macmpi/berryboot-scripts#11]
New direction http://releases.libreelec.tv/

**Comment by macmpi** [comment]
Thanks for using those scripts: hope they are useful.

So you are referring to [installLibreELEC](https://github.com/macmpi/berryboot-scripts/blob/master/LibreELEC/installLibreELEC) script and changed download location & file format.
Also latest version detection will probably fail soon (though still working for now it seems).
Thanks, will look at that when I get some time.

I think updates within LibreELEC app UI (manual or automated) should not be impacted by those infrastructure changes: can you confirm?

**Comment by macmpi** [comment]
FWIW, http://archive.libreelec.tv is still there with releases in .tar format: so script still works as-is.

Automated latest version detection lags to `8.2.5`, but you may manually specify more up-to-date version (like `9.0.2`). That's the first bit that needs fix, but is not critical at this point.
Thanks for the heads-up though.

**Comment by davidcsgf** [comment]
Ok, good news. Yesterday dont run. I update to 9.2beta using the UI and works fine.
Thanks
I Will close this issue

**Comment by macmpi** [comment]
Happy it's not show-stopper yet, but let's keep it open for now, because things seem to be moving in LibreELEC web site, and I will need fix soon anyway...

**Comment by macmpi** [comment]
@davidcsgf feel free to check new version by relaunching installLibreELEC (it will "automagically" pull the new version).
