### ISSUE TITLE
LibreELEC 9.2.0: Restore backup not functioning

### ISSUE THREAD

**Issue by Forusim** [macmpi/berryboot-scripts#13]
Hello @macmpi,
I am not sure, whether it is bug of LibreELEC itself or not, but I cannot restore a backup on LE 9.X.
I am pretty sure, that it worked with LE 8.X.
I am using berryboot-20190612-pi0-pi1-pi2-pi3.zip and created an LE 9.2.0 image with your v1.5 script on Raspbian Buster.
From the LE menu it starts the restore procedure and reboots the device, but after loading the LE image, nothing happens, no restore messages, no errors.
Maybe the data store is handled somehow different and the restore archive is not seen by LE boot process?

**Comment by macmpi** [comment]
If I'm correct, restore/back-up is a LibreELEC plugin, not a core LibreELEC function.
Maybe you need to update your plugin for newer LibreELEC?

**Comment by Forusim** [comment]
No, this is built-in function in the Settings -> LibreELEC -> System
Please refer to their wiki: https://wiki.libreelec.tv/libreelec_settings

**Comment by macmpi** [comment]
Ok, my bad, it's built-in and normally handled by the script.

Restore happens during Berryboot preparation of image, and you may see [some message](https://github.com/macmpi/berryboot-scripts/blob/master/LibreELEC/berryboot-init#L264) on console before LibreELEC splash screen.
Those messages should also be available in system journal once LibreELEC is launched (if you can consult system journal via ssh or console)

What did you back-up (and how), that did not get restored?
Can you clarify the steps

**Comment by Forusim** [comment]
In the described menu I clicked on "Create System and Kodi Backup", that created .tar file on the SD-Card.
I tested something with my database & various configs and wanted to revert to previous state.
So from the same menu I  clicked on "Restore Backup", selected the created .tar file and that was loaded and then system automatically rebooted.
When berryboot loaded the LibreELEC image, in the boot log (white text on black bg) nothing pointed to restore process and LibreELEC just booted like no restore should happen.

**Comment by macmpi** [comment]
Ok.
Out of curiosity, can you elaborate on the exact backup **file name** (and extension) from your SD card? (needs to be 14characters long and .tar)

**Comment by Forusim** [comment]
20200224011248.tar

**Comment by macmpi** [comment]
I do not have mi Pi around, so can't check.
Are you familiar with invoking berryboot console (or over ssh) during startup (before image selection)?
Or would you have a Buster OS OS image installed on which you can do console stuff on (or over ssh)?

**Comment by Forusim** [comment]
Yes, I can.

**Comment by macmpi** [comment]
if you are able to mount /data volume from berryboot, you will see directories corresponding to each images. Assuming your LibreELEC image is named LibreELEC, then you could manually copy your backup file into:`
/data/LibreELEC/storage/.restore/20200224011248.tar`
Then reboot berryboot and select LibreELEC image in berryboot OS chooser to let it boot.
Le me know if you see restoration messages then.

**Comment by Forusim** [comment]
Ok, just tested it with your instructions.
It seems, that you are not allowed to change the name of backup file, what I probably did.
Case can be closed, sorry for the confusion.

**Comment by macmpi** [comment]
Yes that's what I suspected ;)
However any `14characters.tar` name should work, if you still want to customize name.
