### ISSUE TITLE
Issues with the latest build Volumio

### ISSUE THREAD

**Issue by edegraaff** [macmpi/berryboot-scripts#2]
Hi, would you be so kind to look into the folowing issues and give your comment?

https://github.com/volumio/Volumio2/issues/1567
https://volumio.org/forum/multiboot-volumio2-with-kodi-under-berryboot-t6818-20.html
last comment from me

regards

eelco

**Comment by macmpi** [comment]
I already replied there yesterday: lets' avoid cross-posting on same issue (including on Volumio's Github).
Thanks.

**Comment by macmpi** [comment]
@edegraaff did you check-in my reply [in the forum](https://volumio.org/forum/multiboot-volumio2-with-kodi-under-berryboot-t6818-20.html#p50050), and solve your issue finally?
