### ISSUE TITLE
Don't understand your instructions

### ISSUE THREAD

**Issue by FastaOne** [macmpi/berryboot-scripts#4]
How i Upgrade/Update Kodi from 8.0.3 to .0.4.? I dont understand your instructions on your Frontpage. How i do this under Raspbian, starting from BerryBoot. (i have Raspbian Desktop and Kodi installed). What should i write in which file?

**Comment by macmpi** [comment]
Instructions for LibreELEC [are there](https://github.com/macmpi/berryboot-scripts/tree/master/LibreELEC):
It's not specific to moving from 8.0.3 to 8.0.4, but rather installs an upgradable LibreELEC image, that will operate like plain LibreELEC install (with auto/manual updates, data resets, etc..)

- 1st: if you use SD to boot Berryboot please insert `bootdev=mmcblk0p1 ` in `cmdline.txt` file on SD. (If you boot from USB, or other, let me know). Then reboot your device.

- 2nd: launch your Raspbian image under berryboot and get to Terminal application.

- 3rd: copy/paste this command (in one line) and hit return:
`curl -Ls --output installLibreELEC http://bit.do/InstLE; chmod u+x installLibreELEC; ./installLibreELEC`
Follow-on-screen instructions: this will download a LibreELEC image and patch it. You may choose specific version (like 8.0.2 as LibreELEC has no 8.0.3 & jumps to 8.1.0)) or let it get the latest (8.2.5).
From there you will have a new image, that can be upgraded through usual LibreELEC automatic update set-up via UI.

Once you get there (with a functional new LibreELEC image), we can see how to simply get all your settings back from your earlier install (assuming it was LibreELEC already).

**Comment by FastaOne** [comment]
Edit: ok, after it, theres no LibreELEC under "Add OS"
```
pi@raspberrypi:~ $ curl -Ls --output installLibreELEC http://bit.do/InstLE
pi@raspberrypi:~ $ chmod u+x installLibreELEC
pi@raspberrypi:~ $ ./installLibreELEC
 *** Performing self-update
 *** Relaunching after update

#######################################################
########### LibreELEC install on Berryboot  ###########
###########    version  1.0    by macmpi    ###########


This script prepares and installs LibreELEC image for use under berryboot on
Raspberry Pi
It MUST be run under a Debian Linux OS (like Raspbian-lite) and with
internet access.
At first run, it may install missing Debian packages: this can take time...
(sudo rights are needed for Debian installs, mounts and image copy)

If run under Pi with berryboot (recommended), it will try to install image into
final location (SD/USB disk encrypted or not, iSCSI).
If not run under berryboot (Pi, PC,...), it will try to copy image to
any connected media eventually containing a berryboot partition.
If no berryboot data partition is detected, image file may be produced in
working directory, for later-on use...

Hit any key to continue, or "q" to quit 

berryboot kernel detected !! 
Checking berryboot partitions setup

WARNING !!! please fill/add bootdev= statement in cmdline.txt with reference to
your berryboot environment boot partition (mmcblk0p1 or sda1 or else)

Statement shall be in the following form: bootdev=mmcblk0p1 or sda1 or else

Then reboot berryboot system, and try again.
Install will now abort with no change.
```
See Screenshot https://abload.de/img/img_20180729_190733w0el8.jpg

**Comment by macmpi** [comment]
which version did you install with the script? If 8.2.5, then there is no updates available
Under LibreELEC (not OpenELEC), updates happen as follows (one properly setup in LibreELEC UI): LibreELEC will download update (either automatically or when you ask depending on setting), and you may see an onscreen notification when update has been successfully downloaded.

Then you have to restart so that update is actually applied (like in native LibreELEC case): you will see extra messages during image initial startup showing new image processing.

**Comment by macmpi** [comment]
script did quit because you did NOT do step 1!... (read WARNING message)
Upon success, resulting image will be installed & available directly in your boot menu: no need for AddOS.

**Comment by FastaOne** [comment]
i dont know what u mean,
i have this
bootdev=mmcblk0p1
and
installed it under raspbian (look at my post)
i dont know whats wrong

**Comment by macmpi** [comment]
`cmdline.txt` file is at root of you SD FAT partition.
It must have several parameters separated by spaces.
Everything is in **one single** line (no new line/return): the file is composed of one single line.
`bootdev=mmcblk0p1` is one of several other (pre-existing) parameters, as beryboot has set some other important parameters in this file.

**Comment by FastaOne** [comment]
my cmdline.txt look like this https://abload.de/img/img_20180729_190733w0el8.jpg how must it look like (sry for my bad englsih) can you send me in a code or as a txt file?

**Comment by macmpi** [comment]
looks ok, as long as there is no linefeed character.
You can check after booting Raspbian image, go to Terminal and issue:
`cat /proc/cmdline`
and see if it displays every parameters.

**Comment by FastaOne** [comment]
```
cat /proc/cmdline
8250.nr_uarts=0 bcm2708_fb.fbwidth=1280 bcm2708_fb.fbheight=800 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  elevator=deadline quiet bootmenutimeout=10 datadev=mmcblk0p2 qmap=de

```

**Comment by macmpi** [comment]
right, so what we need (`bootdev=mmcblk0p1`) is indeed missing (nothing after `qmap=de`).
So either you introduced a linebreak before (hence made 2 lines), or line is too long.
Are you sure you need all those initial parameters?
Which berryboot version are you using?

**Comment by FastaOne** [comment]
not the latest Version, The Version before,  where can i see this?

**Comment by macmpi** [comment]
Can you turn-off your Pi, remove SD, mount it on your PC/Mac, open `cmdline.txt` file in a plain text editor, and ensure everything is on one line only?

**Comment by FastaOne** [comment]
Thats my cmdline.txt

[cmdline.txt](https://github.com/macmpi/berryboot-scripts/files/2239162/cmdline.txt)

**Comment by macmpi** [comment]
yes there are 2 lines, that's the problem!
Same with all in 1 line...
[cmdline.txt](https://github.com/macmpi/berryboot-scripts/files/2239164/cmdline.txt)

**Comment by FastaOne** [comment]
now it works, almost, but no connect to the raspberry.org Sources for the Debian Tools, Haha, its a Hard Way

**Comment by FastaOne** [comment]
![noconnect](https://user-images.githubusercontent.com/20360460/43370643-49f9582e-9372-11e8-82db-f2c6c5a0a864.jpg)

**Comment by FastaOne** [comment]
sudo apt-get update connection doesnt work. raspberrypi.org down?

**Comment by macmpi** [comment]
**raspbian**.raspberrypi.org is an incorrect source: it should be **archive**.raspberrypi.org
Please **(very carefully)** modify relevant source file in `/etc/apt`

Do you use a old/custom Raspbian install? Those are usually correctly set.

**Comment by FastaOne** [comment]
now I've installed LibreELEC and it works fine, thx for your help!

**Comment by macmpi** [comment]
@Laui77 glad it worked: so the only thing was to properly edit `cmdline.txt `, not adding extra line.
I'm closing this issue; you may close the original one on berriboot github too.
Have fun with your new setup!
(BTW, Volumio2 audio player is great too: made scripts for it too).

**Comment by FastaOne** [comment]
do you know if i can configure the BerryBoot Menü. First i have Raspbian, then LibreELEC, i will change it. it is possible?

**Comment by macmpi** [comment]
Images are sorted by alphabetical order: just rename the image as you wish (you can you it with Berryboot menu): you could add `1_` `2_` in from for instance, or whatever you like.
