### ISSUE TITLE
LibreELEC fail to update to Milhouse build (Kodi 18)

### ISSUE THREAD

**Issue by Forusim** [macmpi/berryboot-scripts#5]
Hello,
I used your script, to create an berryboot image of official 8.2.5 for my Raspberry 3B.
I would like to test the experimental Milhouse build (Kodi 18) from https://forum.kodi.tv/showthread.php?tid=298461
I placed the **LibreELEC-RPi2.arm-9.0-Milhouse-20180731221609-#0731-gaf9932c.tar** in the Update share and reboot.

In the boot screen it says:
> Partitions found: boot: /dev/mmcblk0p1 berryboot data: /dev/mmcblk0p2
> Extracting archive update file...
> Update extracting failed, keeping current image
> Creating Berryboot integration systemd service for LibreELEC OS

Are experimental updates supported by your script?

**Comment by macmpi** [comment]
Hi,
I have never tried/tested it so I have no opinion on whether it may work or not; and as your test shows, it seems it does not (the decompression/install part at least).

There can be several potential problem:
- easy: beta file naming conventions is different from what the script expects with release file-name conventions: this can lead to file management errors (like extraction, file copy, moves, etc) during install as you experienced them.
- more complex: possible image or SW architecture changes: they may arise at runtime. This may need other tweaks in core of the scripts.

I think you can easily work-around the naming convention thing to get the image processed (decompressed, patched & copied over): just renaming the tar file with a fake release-looking name might do the trick.
Alternatively, if you are familiar with doing some basic command-line stuff under ssh or berryboot console, I can explain how to patch enclosed `SYSTEM` image-file, which is the core image that berryboot uses.

If other problems arise at actual image runtime, then this will need more rework: not sure I can dedicate time on this right now.

Let me know how it goes.

**Comment by macmpi** [comment]
Hi, after a quick check, there is indeed a simple naming issue in those beta (enclosed directory within archive does not hold the same name than actual archive file...).
Easy fix: once you copied the archive file in the download directory, slightly rename it by changing `Milhouse` by `devel` (just that, keep all the rest unchanged). Then reboot as before.
With that, extraction & install should go smoothly.

Let me know if the experimental Milhouse build installs fine then, and once run, if it performs as expected.
I may modify the script to remove the naming scheme dependency, depending on your feedback.

**Comment by macmpi** [comment]
ok, so I assume this OK now.
Meanwhile Alpha stage testing [has just started now](https://libreelec.tv/2018/08/libreelec-leia-v8-90-003-alpha/), so you might be able to use UI to get those directly now:
```
LibreELEC 9.0 Alpha 003 (Kodi 18 Alpha 3)

To update an existing installation from within the Kodi GUI select manual update in the LibreELEC settings add-on and then check for updates; select the LibreELEC 9.0 channel and then the 8.90.003 release.
```
However I've [updated script](https://github.com/macmpi/berryboot-scripts/commit/15200d3096a95139dd073ca0fdd612fdc41793e2#diff-473886af906df8d1e835a9e02a282c85) to relax the naming issue, so that it works with Milhouse builds without the need of renaming file anymore.

I'd appreciate if you can test this updated 1.2 version.
You'll get v1.2 automatically along with the next image update you perform: so the fix will materialize as from the second update (when v1.2 is actually run).
Thanks for feedback.

**Comment by Forusim** [comment]
I would like to test the new script, but the URL http://bit.do/InstLE gives me error 500.

**Comment by macmpi** [comment]
Thanks for feedback: indeed it seems bit.do redirector service has some hicups.
You may want to try again (just tested OK).

**Comment by nolsen42** [comment]
Same problem here, now bit.do isn't working AT ALL.

**Comment by macmpi** [comment]
I probably would need to find an alternative provider, but not as simple as it sounds, as there are a few constraints...
Seems back now.
Let me know if v1.2 fixes the issue

**Comment by macmpi** [comment]
@Forusim , @nolsen42 : are you updating Milhouse builds fine now with script v1.2?
Thanks to close the issue if resolved; will do if no further report within a week.

**Comment by macmpi** [comment]
Assumed fixed, as no further reports.
Re-open if not.
