### ISSUE TITLE
LibreELEC reinstall

### ISSUE THREAD

**Issue by FastaOne** [macmpi/berryboot-scripts#6]
Can you explain again how to completely reinstall the current LibreELEC in BerryBoot. Because I have a broken LibreELEC. Do I have to rewrite the cmdline.txt? Or can I just execute the command `curl -Ls --output installLibreELEC http://bit.do/InstLE; chmod u+x installLibreELEC; ./installLibreELEC`?

**Comment by macmpi** [comment]
Hi,
Unless you re-installed berryboot as a whole, `cmdline.txt` is most likely fine: you can check it with berryboot UI (menu editor/Advanced configuration), or under a running raspbian image: `cat /proc/cmdline`

Similarly, you do not necessarily need to "re-download & reinstall" LibreELEC image: berryboot UI allows you to "clone" your image from menu editor: to start with a "fresh" clone, do not copy the filesystem changes.
Alternatively you can indeed run my script from a debian image to re-download & reinstall a fresh and/or different LibreELEC image (newer command below):
`curl -Ls --output installLibreELEC https://bit.ly/InstLibreELEC; chmod u+x installLibreELEC; ./installLibreELEC`

**Comment by FastaOne** [comment]
> `curl -Ls --output installLibreELEC https://bit.ly/InstLibreELEC; chmod u+x installLibreELEC; ./installLibreELEC`

works fine, thanks.
