### ISSUE TITLE
GUI Version of Volumio

### ISSUE THREAD

**Issue by FastaOne** [macmpi/berryboot-scripts#8]
Is there a GUI Version of Volumio available on your berryboot Github?

**Comment by macmpi** [comment]
No there isn't: I do not redistribute Volumio nor any other distribution images.
My scripts do download original images from original sites, and eventually apply some patches to improve Berryboot integration.
I do not distribute Berryboot either; just scripts that can be used with it.
Hope this helps.

**Comment by FastaOne** [comment]
ok thanks
