### ISSUE TITLE
cmdline.txt

### ISSUE THREAD

**Issue by FastaOne** [macmpi/berryboot-scripts#9]
can you tell me again what the cmdline.txt must look like exactly?

**Comment by macmpi** [comment]
Hi, I replied in berryboot issue about your likely problem.
Currently my scripts require `cmdline.txt` have at least `bootdev=something` and `datadev=something`.
the 'something' may be mmcblk0p1, sda1 or else, depending on your drive partition setup (in most cases the former).
`cmdline.txt` is a **single line** text: separator are spaces, and **linefeeds are prohibited**.

It's likely I'll remove the `bootdev` declaration requirement soon.
Feel free to close if it answers your question.

**Comment by Forusim** [comment]
The latest berryboot from 2019-06-12 won´t boot with the "bootdev=mmcblk0p1" setting.
I am booting from SD-Card only.
Without that setting your images will not boot either.
Do you have any suggestions, how to solve this?

**Comment by macmpi** [comment]
Hi.
Yes newer berryboot has a new boot sequence, and some conventions changed. I’ll need to update scripts, but I won’t be able to release for some weeks I’m afraid.
In the  meantime you may try to change initramfs parameter instead as [per this](https://github.com/maxnet/berryboot/issues/581#issuecomment-508489020) 
Let me know how it goes.

**Comment by macmpi** [comment]
I finally updated all scripts to simplify `bootdev` handling and properly support **berryboot 2019-06-12**.
So `bootdev` tweaking is NOT needed anymore: please **remove statement in your `cmdline.txt`** if you use standard SD setup (i.e. not booting from external HD).

Feel free to update your installs (updating your volumio image or other should automagically pull script update too) and report.

@agoldcheidt the produced images should be fine to be distributed now :)

**Comment by Forusim** [comment]
Sorry for the late response.
Just found time to update everything and after some initial issues with older kernel Debian everything works as expected now.
Thanks!
